### ISSUE TITLE
测试集与训练集差距巨大

### ISSUE THREAD

**Issue by yoreG123** [adtalos/AITM-torch#3]
你好，我在复现代码的过程中发现测试集与训练集差距很大，测试集的两个roc只能达到0.5左右的精度，请问有没有什么优化建议呢

**Comment by rockyzhengwu** [comment]
自己数据还是公开数据集？自己数据建议先检查数据，公开数据检查代码

**Comment by yoreG123** [comment]
好的谢谢，我检查一下代码
